[workspace]
members = ["hmac-sha256-circuits", "hmac-sha256"]
resolver = "2"

[workspace.dependencies]
# tlsn
mpz-circuits = { git = "https://github.com/KimiWu123/mpz", rev = "af70e371d96170b7d1726d7ebcd13e41c27dc6e3" }
mpz-common = { git = "https://github.com/KimiWu123/mpz", rev = "af70e371d96170b7d1726d7ebcd13e41c27dc6e3" }
mpz-ot = { git = "https://github.com/KimiWu123/mpz", rev = "af70e371d96170b7d1726d7ebcd13e41c27dc6e3" }
mpz-garble = { git = "https://github.com/KimiWu123/mpz", rev = "af70e371d96170b7d1726d7ebcd13e41c27dc6e3" }

# async
async-trait = "0.1"
futures = "0.3"
tokio = "1"

# error/log
thiserror = "1"
tracing = "0.1"

# testing
criterion = "0.5"
