[package]
name = "tlsn-common"
description = "Common code shared between tlsn-prover and tlsn-verifier"
version = "0.1.0-alpha.7"
edition = "2021"

[features]
default = []
# Enables common types and config parameters used in the AuthDecode protocol. 
# This feature can only be used if the prover and the verifier enable their `authdecode_unsafe` feature.
authdecode_unsafe_common = []

[dependencies]
tlsn-core = { workspace = true }
mpz-common = { workspace = true }
mpz-garble = { workspace = true }
mpz-ot = { workspace = true }

derive_builder = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
serio = { workspace = true, features = ["codec", "bincode"] }
thiserror = { workspace = true }
tracing = { workspace = true }
uid-mux = { workspace = true, features = ["serio"] }
serde = { workspace = true, features = ["derive"] }
tlsn-utils = { workspace = true }
semver = { version = "1.0", features = ["serde"] }

[dev-dependencies]
rstest = { workspace = true }
