name: Test Gramine in SGX Simulation Mode

on:
  push:
  pull_request:

jobs:
  rust_build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Clang
        run: |
          apt update
          apt install -y clang

      - name: Cache Cargo Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: rust-cache-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            rust-cache-${{ runner.os }}-

      - name: Build Rust Binary
        run: |
          cd $GITHUB_WORKSPACE
          cargo build --bin notary-server  --release --features tee_quote
          cp target/release/notary-server $GITHUB_WORKSPACE/notary-server

      - name: Upload Binary for Next Job
        uses: actions/upload-artifact@v4
        with:
          name: notary-server
          path: $GITHUB_WORKSPACE/notary-server

  gramine_sim:
    runs-on: ubuntu-latest
    needs: rust_build
    container:
      image: gramineproject/gramine:latest
      # options: --privileged                         # Required for enclaves in Docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download notary-server binary
        uses: actions/download-artifact@v4
        with:
          name: notary-server
          path: $GITHUB_WORKSPACE/tlsn/crates/notary/server/tee

      - name: Run notary-server in Gramine
        run: |          
          gramine-sgx-gen-private-key

          cd $GITHUB_WORKSPACE/tlsn/crates/notary/server/tee

          gramine-manifest \
            -Dlog_level=debug \
            -Darch_libdir=/lib/x86_64-linux-gnu \
            -Dself_exe=notary-server \
            notary-server.manifest.template \
            notary-server.manifest

          gramine-sgx-sign \
            --manifest notary-server.manifest \
            --output notary-server.manifest.sgx

          # gramine-sgx $GITHUB_WORKSPACE/tlsn/crates/notary/server/tee/notary-server