name: Test Gramine in SGX Simulation Mode

on:
  push:
  pull_request:

jobs:
  gramine_sim:
    runs-on: ubuntu-latest
    container:
      image: gramineproject/gramine:latest  # Use the latest Gramine Docker image
      options: --privileged                         # Required for enclaves in Docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set SGX Simulation Mode
        run: echo "SGX_MODE=SIM" >> $GITHUB_ENV

      - name: Run Hello World in Gramine
        run: |
          apt-get update
          apt-get install git build-essential -y
          gramine-sgx-gen-private-key
          git clone https://github.com/gramineproject/gramine.git
          cd gramine/CI-Examples/helloworld
          make SGX=0
          gramine-sgx ./helloworld