name: Test Gramine in SGX Simulation Mode

on:
  pull_request:

env:
  GIT_COMMIT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
  GIT_COMMIT_TIMESTAMP: ${{ github.event.repository.updated_at}}

jobs:
  rust_build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Clang
        run: |
          apt update
          apt install -y clang

      - name: Cache Cargo Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: rust-cache-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            rust-cache-${{ runner.os }}-

      - name: Build Rust Binary
        run: |
          pwd
          cargo build --bin notary-server  --release --features tee_quote
          find . -iname "notary-server"
          cp --verbose target/release/notary-server $GITHUB_WORKSPACE

      - name: Upload Binary for Next Job
        uses: actions/upload-artifact@v4
        with:
          name: notary-server
          path: notary-server
          if-no-files-found: error

  gramine_sim:
    runs-on: ubuntu-latest
    needs: rust_build
    container:
      image: gramineproject/gramine:latest
      # options: --privileged                         # Required for enclaves in Docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download notary-server binary
        uses: actions/download-artifact@v4
        with:
          name: notary-server
          path: $GITHUB_WORKSPACE/tlsn/crates/notary/server/tee

      - name: Run notary-server in Gramine
        run: |
          # find
          gramine-sgx-gen-private-key

          cd crates/notary/server/tee

          gramine-manifest \
            -Dlog_level=debug \
            -Darch_libdir=/lib/x86_64-linux-gnu \
            -Dself_exe=notary-server \
            notary-server.manifest.template \
            notary-server.manifest

          gramine-sgx-sign \
            --manifest notary-server.manifest \
            --output notary-server.manifest.sgx

          # gramine-sgx $GITHUB_WORKSPACE/tlsn/crates/notary/server/tee/notary-server