name: rustdoc

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Toolchain (Stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: "rustdoc"
        run: cargo doc -p tlsn-core -p tlsn-prover -p tlsn-verifier --no-deps --all-features

      # https://dev.to/deciduously/prepare-your-rust-api-docs-for-github-pages-2n5i
      - name: "Add index file -> tlsn_prover"
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "<meta http-equiv=\"refresh\" content=\"0; url=tlsn_prover\">" > target/doc/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/doc/
